name: Execute JMX Script and Generate HTML Report

on:
  push:
    branches:
      - main

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: docker pull justb4/jmeter:5.5  # Imagem Docker com JMeter

      - name: Run JMeter in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/tests \
            justb4/jmeter:5.5 \
            -n -t /tests/SCRIPT_DesafioPerformance_Carga_v1.jmx -l /tests/report.jtl -e -o /tests/html_report/

      - name: Convert JMeter results to Markdown and HTML
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/tests \
            ubuntu:20.04 bash -c "apt-get update && apt-get install -y pandoc && \
            input_file='/tests/report.jtl' && output_file='/tests/jmeter_results_summary.md' && \
            total_samples=\$(awk -F',' 'NR > 1 {sum += \$2} END {print sum}' \$input_file) && \
            total_errors=\$(awk -F',' 'NR > 1 {sum += \$9} END {print sum}' \$input_file) && \
            error_percentage=\$(awk 'BEGIN {print (\$total_errors/\$total_samples)*100}') && \
            echo '# JMeter Test Summary' > \$output_file && \
            echo 'Total Samples: \$total_samples' >> \$output_file && \
            echo 'Total Errors: \$total_errors' >> \$output_file && \
            echo 'Error Percentage: \$error_percentage%' >> \$output_file && \
            pandoc -f markdown -t html \$output_file -o '/tests/jmeter_results_summary.html'"

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jmeter-results
          path: |
            html_report/
            report.jtl
            jmeter_results_summary.md
            jmeter_results_summary.html
          if-no-files-found: ignore
          retention-days: 2

          retention-days: 2
